###
# Create Site

POST http://localhost:8088/admin/site HTTP/1.1
content-type: application/json

{
    "name":"corporate",
    "url":"www.mysite.com",
    "cors_enabled": false
}

###

# Create RBAC

DELETE http://localhost:8088/site/admin HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJPbmxpbmUgSldUIEJ1aWxkZXIiLCJpYXQiOjE2MzE3Njk0NTMsImV4cCI6MTY2MzMwNTQ1MywiYXVkIjoid3d3LmV4YW1wbGUuY29tIiwic3ViIjoianJvY2tldEBleGFtcGxlLmNvbSIsInJvbGVzIjpbIkNNUyBBRE1JTiIsIkFETUlOIl0sInVzZXIiOiJjbXN1c2VyMSJ9.-ppKailrqrWJZiYUgCXMxoVQbv1l2131M7KllAVZS-M

{
    "path":"/admin",
    "path_match": "STARTSWITH",
    "method": "POST",
    "rbac_role": "CMSADMIN",
    "rbac_user": "user",
    "description":""
}

